changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Product changes
      labels:
        - feature
        - enhancement
    - title: Reliability and security
      labels:
        - bug
        - security
        - reliability
    - title: Documentation and community
      labels:
        - documentation
        - community
    - title: Dependency updates
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
